name: CI/CD for Attrition Prediction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_training.txt
          pip install pytest
      - name: Run tests with coverage and check score
        run: |
          pytest tests/

  build-and-push:
      needs: tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fastapi
          push: true
          tags: luciepienne/attrition-fastapi:latest

      - name: Build and push Streamlit image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.streamlit
          push: true
          tags: luciepienne/attrition-streamlit:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Deployment
        run: |
          echo "Deployment simulation started"
          echo "Deploying FastAPI service..."
          sleep 2
          echo "FastAPI service deployed successfully"
          echo "Deploying Streamlit service..."
          sleep 2
          echo "Streamlit service deployed successfully"
          echo "Deployment simulation completed"

      - name: Deployment Status
        run: echo "Deployment completed successfully!"
  


  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Railway CLI
  #       run: npm i -g @railway/cli@latest

  #     - name: Deploy FastAPI Service
  #       env:
  #         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #       run: railway up --service fastapi-service

  #     - name: Deploy Streamlit Service
  #       env:
  #         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #       run: railway up --service streamlit-service